### ISSUE TITLE
Get Testnet coins from a faucet from within the wallet

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#10]
Integrate https://github.com/bitcoin-sv/bsv-faucet or any working BSV testnet faucet so that devs or users that are using testnet can easily get coins into their wallet when using a Testnet account.

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Identify parts of code that needs to be changed or updated
3. Make necessary changes
4. Add tests to make sure the changes are working and no adverse effects
5. And lastly optimize

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a solid blockchain developer and third-party API integration. Proficient in Node.js, React, and API development, I have also contributed to open-source projects. My background in user-friendly interfaces and service integrations makes me well-suited for this project.

### How I plan on tackling this issue
Problem Approach: I will create a simple API wrapper for the BSV faucet to handle requests and responses. This will include rate limiting, error handling, and a user-friendly interface for requesting testnet coins. Additionally, I will validate wallet addresses and implement logging to monitor usage and identify potential issues.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
To integrate a working BSV Testnet faucet (e.g., from https://github.com/bitcoin-sv/bsv-faucet), I would follow these steps:

Set Up the Faucet API: I will either deploy the BSV faucet from the repository or use any publicly available BSV Testnet faucet API to request testnet coins. This API will allow users to receive testnet BSV by simply providing their wallet address.
Add a "Get Testnet Coins" Button: In the wallet interface, specifically for Testnet accounts, I’ll add a button labeled “Get Testnet Coins.” This button will only appear when a user is on Testnet.
Request Coins from the Faucet: When the user clicks the “Get Testnet Coins” button, the wallet will call the faucet API, passing the user’s Testnet wallet address. The API will send a small amount of BSV to that address.
Display Transaction Information: After the request is sent, I’ll provide feedback to the user, such as displaying the transaction details or a confirmation message. I’ll also handle potential errors, like faucet downtime or failure to send coins.
Test the Integration: I will test the integration thoroughly by sending coins to a Testnet account and ensuring that the faucet interacts correctly with the wallet interface.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To integrate a BSV Testnet faucet within the wallet, I will implement a feature allowing users to request Testnet coins directly from the wallet interface. By integrating an available faucet like the one from `https://github.com/bitcoin-sv/bsv-faucet` or another working BSV Testnet faucet, users and developers working in Testnet mode will be able to easily fund their accounts. The wallet will detect if the user is on the Testnet network and display an option to request Testnet coins. The integration will include a simple button that interacts with the faucet API, automatically sending coins to the user's wallet address for seamless testing.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have some experience on blockchain and want to contribute actively to the projects and want to solve the issues. 

### How I plan on tackling this issue
To integrate the BSV Testnet faucet, I will:

Install faucet API using the repository from https://github.com/bitcoin-sv/bsv-faucet or another working testnet faucet.
Add a "Get Testnet Coins" button that should be shown only in Testnet mode so users can request testnet BSV.
Implement error handling and validation on wallet address so that the user experience is friendly. Test it good to ensure seamless interaction between the wallet and the faucet API.

**Comment by Ekene001** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I'm Ekene, a frontend and blockchain developer, and I’m new to the OnlyDust platform. This is my first time contributing to this repository, and I’m excited about the opportunity to collaborate and bring my skills to the table. Looking forward to making a positive impact and working with the team!

### How I plan on tackling this issue
To tackle this task, I will start by identifying a reliable and functional BSV testnet faucet, beginning with the bsv-faucet repository or finding an alternative if needed. I’ll evaluate the chosen faucet's API to understand how to interact with its endpoints, handle authentication, and work within any transaction limits, ensuring a stable service for continuous use.

Once I select the faucet, I’ll proceed to integrate it by setting up a backend service that interacts with the faucet's API to request testnet coins. I’ll develop a user-friendly interface where users can input their testnet wallet address, and the backend will automatically initiate the request for coins. I'll implement proper error handling and provide clear feedback so users know when their requests are successful or if any issues arise.

After the integration, I’ll thoroughly test the solution to ensure coins are reliably dispensed to testnet accounts. I'll consider any API rate limits and prepare strategies for switching faucet providers or caching requests if necessary to maintain consistent performance.

Finally, I’ll create detailed documentation to guide users through the process of using the faucet integration, including steps to obtain testnet coins and troubleshoot any common issues. This will make the integration accessible and easy for developers and users alike.

**Comment by mimisavage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hi, I’m Mimi Sav, a frontend and blockchain developer. This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.



### How I plan on tackling this issue
To tackle the integration of a BSV testnet faucet, I plan to create a streamlined process for developers and users to easily obtain testnet coins.

In summary, my approach involves selecting a reliable BSV testnet faucet, like the one available on the Bitcoin SV GitHub, and incorporating it into our platform. This will allow users to request coins directly to their testnet wallets with minimal effort.

I will begin by evaluating the available faucet options to ensure they function correctly and provide a steady supply of coins. Next, I will develop a user-friendly interface where users can enter their testnet wallet addresses to request coins. I will implement backend functionality to securely interact with the chosen faucet’s API, ensuring efficient handling of requests. After thorough testing to confirm everything works smoothly, I will roll out the feature to our users.

**Comment by danwag06** [comment]
@0xdevcollins please confirm assignment

**Comment by 0xdevcollins** [comment]
@danwag06 Thank you sir. will get to work immediately

**Comment by 0xdevcollins** [comment]
Hi @danwag06 please where can I contact you?

**Comment by danwag06** [comment]
@0xdevcollins I'm @danwag06 on telegram
