### ISSUE TITLE
Select and transfer multiple 1sat ordinal NFTs in same transaction

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#3]
A user should be able to select and send multiple NFTs in the same transaction. At the very least they should be able to select and send to a single address. A bonus would be for the user to be able to customize the recipient addresses for each selected NFT.

If you are unfamiliar with inscriptions/1sat ordinals you can easily inscribe them to your wallet by using the `inscribe` provider method 👉  https://yours-wallet.gitbook.io/provider-api/ordinals/inscribe

To learn more about 1sat ordinals 👉 https://1satordinals.com/

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study design
2. Research on Multisend of ordinals and inscriptions.
3. Implement the Multisend features
4. Add tests
5. And lastly optimize.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have some experience in blockchain development and want to contribute to open source and fix the issues. 

### How I plan on tackling this issue
First and foremost, I should add the bulk send feature allowing users to select multiple 1sat Ordinal NFTs and send them in a single transaction with an option either to send all to one address or customize recipient addresses for each NFT. That way the experience of the user will be more streamlined and variable NFT transfers will be improved.

**Comment by ooochoche** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I am a smart contract developer

### How I plan on tackling this issue
I've read the description and I am equipped to fix the issue

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hello @danwag06, I would love to handle this...

### How I plan on tackling this issue

Here's how I will implement this feature step by step:

1. NFT Selection:
   - Create a grid/list view of available NFTs
   - Allow users to select multiple NFTs using checkboxes/toggles
   - Store selected NFTs in state array

2. Recipient Configuration:
   - Add a toggle between single/multiple recipient modes
   - For single recipient: Show one address input field
   - For multiple recipients: Show address input for each selected NFT

3. Transaction Handling:
   - Create a batch transaction object with selected NFTs and their recipients
   - Use wallet provider's sendBatchTransaction method
   - Handle success/error states appropriately

4. User Experience:
   - Validate addresses before enabling send button
   - Show clear feedback during transaction process
   - Allow deselection of NFTs

5. Error Handling:
   - Validate recipient addresses
   - Check for sufficient balance/permissions
   - Provide clear error messages to users

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have a strong background in blockchain development and front-end technologies, with extensive experience in creating decentralized applications (dApps) that interact with smart contracts and digital assets. My expertise includes working with NFT standards and implementing user-friendly interfaces that facilitate complex transactions. Additionally, I am familiar with working with ordinals and have experience with integrating wallet functionalities for seamless transactions. This background positions me well to implement the feature for selecting and sending multiple NFTs in a user-friendly manner.



### How I plan on tackling this issue

To enable users to select and send multiple NFTs in a single transaction, I would:

1. Enhance the UI: Design a user-friendly interface that allows users to select multiple NFTs, with checkboxes for selection and input fields for customizing recipient addresses.

2. Modify Transaction Logic: Update the existing NFT sending function to handle multiple NFTs and their respective recipient addresses, ensuring efficient data handling.

3. Implement Validation: Add input validation for recipient addresses to prevent errors and ensure proper transaction execution.

4. Test Functionality: Conduct thorough testing to verify that users can successfully send multiple NFTs to different addresses, including edge cases and error handling.

5. Document Changes; Update documentation to guide users on how to utilize the new multi-send feature effectively.

This approach will provide a seamless experience for users when sending multiple NFT

**Comment by danwag06** [comment]
@JoE11-y please confirm assignment

**Comment by JoE11-y** [comment]
Confirmed will begin working on it.

**Comment by Jemiiah** [comment]
@danwag06 pls can I work on this issue quickly a short time frame left to complete OD Hack

**Comment by danwag06** [comment]
@Jemiiah https://github.com/bitcoin-sv/spv-wallet-browser/pull/21#issuecomment-2444792892

If they can't get it done, I will ping you.

**Comment by Jemiiah** [comment]
Alright ser 🙃 @danwag06
