### ISSUE TITLE
Add tests and CI

### ISSUE THREAD

**Issue by danwag06** [bitcoin-sv/spv-wallet-browser#6]
Once a testing framework is set up, contributors can add their own test cases, which can be put in a CI like Travis or Github Action.

**Comment by mexes20** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hey @danwag06 can I work on this?

Here is a sample of a CI I setup for a project recently 
https://github.com/keep-starknet-strange/raito/issues/159

**Comment by Akshola00** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I'm a software developer experienced in web development and open-source projects, with a background in testing frameworks and automation tools specially with github actions.

### How I plan on tackling this issue
I will set up a GitHub Actions workflow that runs tests on every pull request, including automated execution, coverage reporting, and status checks. I will also provide clear documentation for contributors on adding new tests and maintain a template structure for easy expansion of the test suite.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have some experience in blockchain development and want to actively participate in open source.

### How I plan on tackling this issue
I will implement a GitHub Actions workflow to automate test runs on every pull request, which would include running the test suite, generation of coverage reports, and enforcement of status checks. It will, of course, be properly documented with instructions for contributors on how new test cases could easily be added.

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I'm nik, im an experienced blockchain and linux developer, i habe worked on many CI/CD projects before.

### How I plan on tackling this issue
i will need less than a day to fix this

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 4 years experience

Here's my OnlyDust profile https://app.onlydust.com/u/raizo07

ETA: One day

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/spv-wallet-browser).

### My background and how it can be leveraged
I have experience in setting up testing frameworks and integrating continuous integration (CI) tools like Travis and GitHub Actions in software projects.

### How I plan on tackling this issue
I would establish a testing framework compatible with the project, then configure CI pipelines in Travis or GitHub Actions to automate test execution on each commit. This setup would enable contributors to easily add and run their own test cases, ensuring code quality and reliability.

**Comment by ShantelPeters** [comment]
Thank you 🚀
